### ISSUE TITLE
Where can i download the apk file?

### ISSUE THREAD

**Issue by ghost** [mslalith/focus_launcher#11]
I cannot find the apk file to download and install the app.

**Comment by mslalith** [comment]
@abyseku app is still WIP but there's an open testing build on [Play Store](https://play.google.com/store/apps/details?id=dev.mslalith.focuslauncher), you can use that

**Comment by IzzySoft** [comment]
Is there a way to get it without Google's walled garden, @mslalith? Maybe you could attach it to its corresponding [release](https://github.com/mslalith/focus_launcher/releases) so those without access to Play can give it a try? Open Source shouldn't have closed doors :wink:

**Comment by mslalith** [comment]
@IzzySoft thanks for pointing out. I've updated Releases. Do checkout

**Comment by IzzySoft** [comment]
Thanks a lot! Spreading the word, your app should [become available here](https://apt.izzysoft.de/fdroid/index/apk/dev.mslalith.focuslauncher) within about an hour (daily update checks). Just wondering what for these two libraries are needed in a launcher:

```
Offending libs:
---------------
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Google Play Core (/com/google/android/play/core): NonFreeNet,NonFreeDep

2 offenders.
```

They are currently "tainting" your app as they are non-free – and I guess they are also responsible for the network permissions which would otherwise not be needed. No complaints, just letting you know in case they were "dragged in" unintentionally. In case you don't even have an idea what brought them in: `gradle :app:dependencies` might help you finding out.

Thanks again for making the app available to the world outside the "walled garden"!

**Comment by mslalith** [comment]
These are from App update library. I added Check for Updates feature earlier but removed later. I'll clean up in the next release

**Comment by IzzySoft** [comment]
Thanks!
